api_platform:
    # Set this to false if you want Webby to disappear.
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/config/api_platform']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
