resources:
    App\Entity\ApiKey:
        collectionOperations: []
        itemOperations:
            get:
                method: GET
                controller: ApiPlatform\Core\Action\NotFoundAction
                read: false
                output: false
                openapi_context:
                    summary: hidden