resources:
    App\Entity\Category:
        collectionOperations:
            get:
                method: GET
            post:
                method: POST
        itemOperations:
            put:
                method: PUT
            delete:
                method: DELETE
            patch:
                method: PATCH
            get:
                method: GET
                openapi_context:
                    summary: hidden
                read: false
                output: false