resources:
    App\Entity\User:
        attributes:
            security: 'is_granted("ROLE_USER")'
            normalization_context:
                groups: ['read:user']
        collectionOperations: []
        itemOperations:
            get:
                controller: ApiPlatform\Core\Action\NotFoundAction
                read: false
                output: false
                openapi_context:
                    summary: hidden
            me:
                method: GET
                pagination_enabled: false
                path: /me
                controller: App\Controller\MeController
                read: false
                openapi_context:
                    security:
                        - bearerAuth: []