resources:
    App\Entity\User:
        attributes:
            security: 'is_granted("ROLE_USER")'
        collectionOperations: []
        itemOperations:
            get:
                method: GET
                controller: ApiPlatform\Core\Action\NotFoundAction
                read: false
                output: false
                openapi_context:
                    summary: hidden
            me:
                method: GET
                pagination_enabled: false
                path: /me
                read: false
                controller: App\Controller\MeController
                normalization_context:
                    groups: [ 'read:user:me' ]
                openapi_context:
                    security:
                        - bearerAuth: []