resources:
    App\Entity\User:
        attributes:
            normalization_context:
                groups: ['read:user']
        collectionOperations: []

        itemOperations:
            me:
                method: GET
                pagination_enabled: false
                path: /me
                controller: App\Controller\MeController
                read: false
                security: 'is_granted("ROLE_USER")'
                openapi_context:
                    security:
                        -   cookieAuth: [ ]